language: cpp
jobs:
  include:
  - os: linux
    compiler: gcc
    sudo: require
    dist: xenial
  - os: osx
    osx_image: xcode7.2
    compiler: gcc
  - os: windows

before_install:
  - |-
      case $TRAVIS_OS_NAME in
        linux)
          sudo add-apt-repository ppa:beineri/opt-qt-5.11.1-xenial -y
          sudo apt-get update -qq
          ;;
        windows)
          [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
          choco uninstall -y mingw
          choco upgrade --no-progress -y msys2
          export msys2='cmd //C RefreshEnv.cmd '
          export msys2+='& set MSYS=winsymlinks:nativestrict '
          export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
          export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
          export msys2+=" -msys2 -c "\"\$@"\" --"
          $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
          ## Install more MSYS2 packages from https://packages.msys2.org/base here
          taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
          export PATH=/C/tools/msys64/mingw64/bin:$PATH
          export MAKE=mingw32-make  # so that Autotools can find it
        ;;
      esac

install:
  - |-
      case $TRAVIS_OS_NAME in
        linux)
          sudo apt-get -y install qt511base libgl1-mesa-dev
          source /opt/qt*/bin/qt*-env.sh
          ;;
        osx)
          brew install qt5
          ;;
        windows)
          $msys2 pacman --sync --clean --noconfirm
          $msys2 pacman -S --noconfirm base-devel git mercurial cvs wget p7zip
          $msys2 pacman -S --noconfirm perl ruby python2 mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain
          $msys2 pacman -S --noconfirm mingw-w64-i686-qt5-static mingw-w64-x86_64-qt5-static
          $msys2 pacman -S --noconfirm mingw-w64-x86_64-zlib zlib-devel
          $msys2 pacman -S --noconfirm mingw-w64-x86_64-openssl openssl-devel
          export QT_MSYS2=true
          ;;
      esac

script:
  - |-
      case $TRAVIS_OS_NAME in
        linux)
          qmake CONFIG+=release PREFIX=/usr
          make -j$(nproc)
          mkdir -p appdir/usr/bin
          cp QTjsonDiff appdir/usr/bin/QTjsonDiff
          mkdir -p appdir/usr/share/icons/
          cp diff.png appdir/usr/share/icons/
          mkdir -p appdir/usr/share/applications/
          cp qtjsondiff.desktop appdir/usr/share/applications/
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
          ;;
        osx)
          chmod 777 MAC_build_RELEASE.sh
          ./MAC_build_RELEASE.sh
          ;;
        windows)
          $msys2 export QT_MSYS2_ARCH=386
          $msys2 export QT_MSYS2_STATIC=true
          $msys2 QMAKE_CXX=g++
          $msys2 /c/tools/msys64/mingw32/qt5-static/bin/qmake.exe
          #$msys2 /tools/msys64/mingw64/qt5-static/bin/qmake.exe
          $msys2 ls -l /c/tools/msys64/mingw32/qt5-static/bin
          $msys2 ls -l /c/tools/msys64/mingw32/bin
          $msys2 /c/tools/msys64/mingw32/bin/mingw32-make.exe
          #$msys2 /c/tools/msys64/mingw64/bin/mingw32-make.exe
          $msys2 ls -l
      esac

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash upload.sh Qt*.AppImage*                                         ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash upload.sh QT*.zip QT*.dmg                                        ; fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
